### ISSUE TITLE
ITV Have Broken GetFlashVideos

### ISSUE THREAD

**Issue by cemacf** [njtaylor/get-flash-videos#3]
Within the last few days changes to the ITV player site have broken get_flash_videos.  Example (will
linewrap):

perl C:\Programs\GetFlashVideos\get_flash_videos http://www.itv.com/hub/tommy-cooper/L1059a0006

Using method 'itv' plugin version 0.06 for
http://www.itv.com/hub/tommy-cooper/L1059a0006
Downloading http://www.itv.com/hub/tommy-cooper/L1059a0006
Error: No id (filter) found in URL or production id

Couldn't extract Flash movie URL. This site may need specific support adding, or fixing.

The same thing occurs on four different machines, at least two of which were working just a few days ago:
    Ubuntu 14
    Windows 2000
    Windows XP
    Windows 7

**Comment by njtaylor** [comment]
You need an update from 0.06 version to 0.07 for the ITV site - lib/flashVideos/Site/Itv.pm has been updated,  see under releases, release 1.25.91 on 
https://github.com/monsieurvideo/get-flash-videos includes downloads.

$ get_flash_videos http://www.itv.com/hub/tommy-cooper/L1059a0006
Using method 'itv' plugin version 0.07 for http://www.itv.com/hub/tommy-cooper/L1059a0006
Downloading http://www.itv.com/hub/tommy-cooper/L1059a0006
RTMPDump v2.4-git-a107cef9 KSV-2015-05-05
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Connected...
Starting download at: 0.000 kB
INFO: Metadata:
INFO:   duration                1426.24
INFO:   moovPosition            32.00
INFO:   width                   672.00
INFO:   height                  504.00
INFO:   videocodecid            avc1
INFO:   audiocodecid            mp4a
INFO:   avcprofile              100.00
INFO:   avclevel                31.00

**Comment by cemacf** [comment]
Many thanks.  Have now fixed the problem on Ubuntu, so presumably the others will be alright as well.

Incidentally, there is an extra perl module required by this latest version:
    cpan Term::ProgressBar

Admirably quick response.  Many congratulations and thanks to all those involved.
 

 -----Original Message-----
